USE ODS

DROP TABLE IF EXISTS euro.EurostatData

GO

DROP SCHEMA IF EXISTS euro

GO

CREATE SCHEMA euro

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE euro.EurostatData(
[ETLKey] [uniqueidentifier] NOT NULL,
DECLARANT NVARCHAR(255) NULL,
DECLARANT_ISO NVARCHAR(255) NULL,
PARTNER NVARCHAR(255) NULL,
PARTNER_ISO NVARCHAR(255) NULL,
TRADE_TYPE NVARCHAR(255) NULL,
PRODUCT_NC NVARCHAR(255) NULL,
PRODUCT_SITC NVARCHAR(255) NULL,
PRODUCT_CPA2002 NVARCHAR(255) NULL,
PRODUCT_cpa2008 NVARCHAR(255) NULL,
PRODUCT_CPA2_1 NVARCHAR(255) NULL,
PRODUCT_BEC NVARCHAR(255) NULL,
PRODUCT_SECTION NVARCHAR(255) NULL,
FLOW NVARCHAR(255) NULL,
STAT_REGIME NVARCHAR(255) NULL,
SUPP_UNIT NVARCHAR(255) NULL,
PERIOD NVARCHAR(255) NULL,
VALUE_IN_EUROS NVARCHAR(255) NULL,
QUANTITY_IN_KG NVARCHAR(255) NULL,
SUP_QUANTITY NVARCHAR(255) NULL,
[UniqueDims] [varbinary](35) NULL,
[UniqueRows] [varbinary](16) NULL,
[SourceSystem] [nvarchar](255) NULL,
[Cleansed] [bit] NULL,
[ErrorRecord] [bit] NULL,
[ErrorReason] [nvarchar](255) NULL,
[Processed] [bit] NULL,
[RunDate] [datetime] NULL,
 CONSTRAINT [PK_EurostatData] PRIMARY KEY CLUSTERED 
(
       [ETLKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [euro].[EurostatData] ADD  CONSTRAINT [DF_EurostatData_ETLKey]  DEFAULT (newid()) FOR [ETLKey]
GO

ALTER TABLE [euro].[EurostatData] ADD  CONSTRAINT [DF_EurostatData_SourceSystem]  DEFAULT (N'Eurostat') FOR [SourceSystem]
GO

ALTER TABLE [euro].[EurostatData] ADD  CONSTRAINT [DF_EurostatData_Cleansed]  DEFAULT ((0)) FOR [Cleansed]
GO

ALTER TABLE [euro].[EurostatData] ADD  CONSTRAINT [DF_EurostatData_ErrorRecord]  DEFAULT ((0)) FOR [ErrorRecord]
GO

ALTER TABLE [euro].[EurostatData] ADD  CONSTRAINT [DF_EurostatData_Processed]  DEFAULT ((0)) FOR [Processed]
GO

ALTER TABLE [euro].[EurostatData] ADD  CONSTRAINT [DF_EurostatData_RunDate]  DEFAULT (getdate()) FOR [RunDate]
GO



